# Generated by Django 5.2 on 2025-05-08 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wastereport",
            name="collected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wastereport",
            name="date_reported",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
