# Generated by Django 5.2 on 2025-05-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Services", "0002_wastereport_collected_wastereport_date_reported"),
    ]

    operations = [
        migrations.AddField(
            model_name="wastereport",
            name="proof_image",
            field=models.ImageField(blank=True, null=True, upload_to="proof_images/"),
        ),
        migrations.AlterField(
            model_name="wastereport",
            name="date_reported",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
