# Generated by Django 5.2 on 2025-05-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Services", "0003_wastereport_proof_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wastereport",
            name="reward_given",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
