# Generated by Django 5.2 on 2025-05-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reward",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
